theme: jekyll-theme-slate

body {
background-color: #FCF7F8;
border: 2px solid gray;
border-radius: 16px;
font-family: sans-serif;
margin-left: auto;
margin-right: auto;
max-width: 1024px;
min-width: 256px;
padding-top: 8px;
padding-bottom: 24px;
padding-left: 24px;
padding-right: 24px;
}

html {
background: radial-gradient(circle, #5B616A, #275DAD 50%, #CED3DC 50%, #5B616A);
background-size: 10px 10px;
}

h1 {
background-color:#FCF7F8;
color: #5B616A;
font-family: cursive;
font-weight: bold;
font-size: 32px;
}

h2 {
background-color:#FCF7F8;
color: #5B616A;
font-family: cursive;
font-size: 19px;
}

h3 {
background-color:#FCF7F8;
color: #5B616A;
font-family: cursive;
font-size: 16px;	
}

#para1 {
text-align:centre;
color: black;
}

ul {
}

nav ul {
list-style-type:round;
border: 4px solid gray;
border-radius: 6px;
font-family: sans-serif;
font-weight: bold;
font-size: 15px;
padding: 8px;
}

nav ul li {
display: inline;
border-right: 2px
solid #5B616A;
padding-right: 8px;
padding-left: 8px;
}

nav ul li:last-child { 
border-right: none;
}

nav ul li a {
text-decoration:none;
}	

nav li.selected {
color: #606060;
}

nav li a:hover {
text-decoration: underline;
}

p.top-tip {
border: 4px dashed #275DAD;
border-radius: 10px;
padding: 16px;
background-color: #ABA9C3;
}

p.top-tip::before {
color: Black;
content: "MEGA TIP!: ";
font-weight: bold;
}

p {
color:black;
text-align: centre;
}

table {
font-size: 80%;
border-collapse: collapse;
width: 100%;
text-align: left;
}

th, td {
border: 1px solid #5B616A;
padding: 8px;
text-align: left;
}

th {
background-color: #CED3DC;
}

td {
background-color: #ABA9C3;
}

a:link {
color: blue;
}

a:visited {
color: purple;
}

a:hover {
text-decoration: underline;
}

a:active {
text-decoration: underline;
background-color: black;
color: white;
}
